### ISSUE TITLE
Document pipeline

### ISSUE THREAD

**Issue by berleon** [BioroboticsLab/bb_pipeline#4]
Document how to use the pipeline. Maybe we can write a short tutorial.

**Comment by nebw** [comment]
We could certainly add more documentation, but I consider this mostly done since commits e545af7fc16bd5836f18fad95ef45d546d130009 and 93f6c11c39a8985ed7dbeeb4199fb561e8f9260e . Let's handle this in more specific issues in the future if the need for more documentation arises since 'Add documentation' is a open ended ticket ;)
